export MAIN_INCLUDE=yes

VAR_INIT = $(if $(shell sed -n "s/$1=//p" $(CURDIR)/.config),$(shell sed -n "s/$1=//p" $(CURDIR)/.config),$(2))

export DEFAULT_CXX := $(CXX)
export DEFAULT_PREFIX := /usr
export SED_DEFAULT_PREFIX := $(subst /,\/,$(DEFAULT_PREFIX))

export CXX := $(call VAR_INIT,CXX,$(DEFAULT_CXX))
export USE_LIBXML := $(call VAR_INIT,USE_LIBXML,y)
export BUILD_SRC := $(call VAR_INIT,BUILD_SRC,y)
export BUILD_UTIL := $(call VAR_INIT,BUILD_UTIL,y)

export PREFIX := $(call VAR_INIT,PREFIX,$(DEFAULT_PREFIX))
export SED_PREFIX := $(subst /,\/,$(PREFIX))
