name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ubuntu dependences
      run: sudo apt install make libboost-system-dev libxml++2.6-dev mysql-server
    - name: Load mysql dump
      run: mysql test_db < backup-file.sql
    - name: make
      run: make
      
